const doctorData = [
    {
      "name":"Dr. Rogers William",
      "specialist":"Dermatologist",
      "phone":"8638801035",
      "hospital":"Heartbeat Care Clinic",
      "onlineHours":"Wed-Wed, 11 PM - 2 AM",
      "hospitalHours":"Tue-Sun, 2 PM - 5 PM",
      "weekendAvailability":"Fri, 5 PM - 8 PM",
      "emergencyAvailable":true,
      "photo":"https://randomuser.me/api/portraits/men/0.jpg"
    },
    {
      "name":"Dr. Melissa Perez",
      "specialist":"Dermatologist",
      "phone":"9706796453",
      "hospital":"Evergreen Hospital",
      "onlineHours":"Wed-Fri, 8 AM - 11 AM",
      "hospitalHours":"Wed-Wed, 6 PM - 9 PM",
      "weekendAvailability":"Sun, 9 AM - 12 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/1.jpg"
    },
    {
      "name":"Dr. Bonnie Adams",
      "specialist":"Gastroenterologist",
      "phone":"9843119401",
      "hospital":"Metro General Hospital",
      "onlineHours":"Mon-Wed, 7 PM - 10 PM",
      "hospitalHours":"Tue-Tue, 10 AM - 1 PM",
      "weekendAvailability":"Sun, 6 PM - 9 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/2.jpg"
    },
    {
      "name":"Dr. Kimberly Green",
      "specialist":"orthopedic Surgeon",
      "phone":"5560255774",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Fri-Sun, 2 PM - 5 PM",
      "hospitalHours":"Thu-Sun, 10 AM - 1 PM",
      "weekendAvailability":"Sun, 7 PM - 10 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/3.jpg"
    },
    {
      "name":"Dr. Todd Nichols",
      "specialist":"Dermatologist",
      "phone":"5448501125",
      "hospital":"Lakeside Medical Center",
      "onlineHours":"Sun-Thu, 2 PM - 5 PM",
      "hospitalHours":"Tue-Fri, 3 PM - 6 PM",
      "weekendAvailability":"Fri, 11 PM - 2 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/4.jpg"
    },
    {
      "name":"Dr. Deborah Walsh",
      "specialist":"Dermatologist",
      "phone":"6898475852",
      "hospital":"SummitCare Clinic",
      "onlineHours":"Sun-Fri, 9 AM - 12 PM",
      "hospitalHours":"Wed-Tue, 2 PM - 5 PM",
      "weekendAvailability":"Fri, 7 PM - 10 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/5.jpg"
    },
    {
      "name":"Dr. Juan Bradley",
      "specialist":"Gastroenterologist",
      "phone":"3628315800",
      "hospital":"Blue Ridge Medical",
      "onlineHours":"Sat-Fri, 9 AM - 12 PM",
      "hospitalHours":"Tue-Sun, 9 AM - 12 PM",
      "weekendAvailability":"Sat, 2 PM - 5 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/6.jpg"
    },
    {
      "name":"Dr. Stephanie White",
      "specialist":"Neurologist",
      "phone":"2805895243",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Sun-Mon, 7 PM - 10 PM",
      "hospitalHours":"Thu-Sun, 6 PM - 9 PM",
      "weekendAvailability":"Sat, 5 PM - 8 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/7.jpg"
    },
    {
      "name":"Dr. Jimmy Clark",
      "specialist":"Gastroenterologist",
      "phone":"9927032285",
      "hospital":"Blue Ridge Medical",
      "onlineHours":"Mon-Thu, 2 PM - 5 PM",
      "hospitalHours":"Sun-Wed, 10 AM - 1 PM",
      "weekendAvailability":"Sun, 8 AM - 11 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/8.jpg"
    },
    {
      "name":"Dr. Jennifer Wallace",
      "specialist":"Radiologist",
      "phone":"8241076227",
      "hospital":"Evergreen Hospital",
      "onlineHours":"Wed-Wed, 9 AM - 12 PM",
      "hospitalHours":"Wed-Fri, 3 PM - 6 PM",
      "weekendAvailability":"Fri, 9 AM - 12 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/9.jpg"
    },
    {
      "name":"Dr. Raymond Davis",
      "specialist":"Pediatrician",
      "phone":"0425998925",
      "hospital":"Evergreen Hospital",
      "onlineHours":"Thu-Mon, 8 AM - 11 AM",
      "hospitalHours":"Mon-Tue, 7 PM - 10 PM",
      "weekendAvailability":"Wed, 10 AM - 1 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/10.jpg"
    },
    {
      "name":"Dr. Jennifer Decker",
      "specialist":"Endocrinologist",
      "phone":"3962271991",
      "hospital":"Heartbeat Care Clinic",
      "onlineHours":"Tue-Fri, 9 AM - 12 PM",
      "hospitalHours":"Mon-Wed, 10 AM - 1 PM",
      "weekendAvailability":"Sat, 8 AM - 11 AM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/11.jpg"
    },
    {
      "name":"Dr. David Thompson",
      "specialist":"Dermatologist",
      "phone":"6788427304",
      "hospital":"Blue Ridge Medical",
      "onlineHours":"Mon-Sat, 2 PM - 5 PM",
      "hospitalHours":"Sat-Mon, 7 PM - 10 PM",
      "weekendAvailability":"Wed, 10 AM - 1 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/12.jpg"
    },
    {
      "name":"Dr. Michael Hernandez",
      "specialist":"Neurologist",
      "phone":"3981067888",
      "hospital":"SummitCare Clinic",
      "onlineHours":"Wed-Mon, 3 PM - 6 PM",
      "hospitalHours":"Fri-Thu, 6 PM - 9 PM",
      "weekendAvailability":"Sun, 8 AM - 11 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/13.jpg"
    },
    {
      "name":"Dr. Wanda Hess",
      "specialist":"Endocrinologist",
      "phone":"2264648783",
      "hospital":"SummitCare Clinic",
      "onlineHours":"Fri-Wed, 7 PM - 10 PM",
      "hospitalHours":"Sat-Fri, 11 PM - 2 AM",
      "weekendAvailability":"Sun, 9 AM - 12 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/14.jpg"
    },
    {
      "name":"Dr. David Alexander",
      "specialist":"Cardiologist",
      "phone":"1572911275",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Thu-Tue, 7 PM - 10 PM",
      "hospitalHours":"Mon-Sat, 5 PM - 8 PM",
      "weekendAvailability":"Fri, 5 PM - 8 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/15.jpg"
    },
    {
      "name":"Dr. Charles Wood",
      "specialist":"Endocrinologist",
      "phone":"7632871506",
      "hospital":"WellSpring Hospital",
      "onlineHours":"Fri-Fri, 8 AM - 11 AM",
      "hospitalHours":"Thu-Thu, 6 PM - 9 PM",
      "weekendAvailability":"Mon, 5 PM - 8 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/16.jpg"
    },
    {
      "name":"Dr. Bonnie Castillo",
      "specialist":"Gastroenterologist",
      "phone":"3737427653",
      "hospital":"Heartbeat Care Clinic",
      "onlineHours":"Sat-Wed, 7 PM - 10 PM",
      "hospitalHours":"Thu-Tue, 9 AM - 12 PM",
      "weekendAvailability":"Tue, 5 PM - 8 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/17.jpg"
    },
    {
      "name":"Dr. Erica Murillo",
      "specialist":"orthopedic surgeon",
      "phone":"2676354819",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Sat-Wed, 3 PM - 6 PM",
      "hospitalHours":"Tue-Mon, 9 AM - 12 PM",
      "weekendAvailability":"Thu, 10 AM - 1 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/18.jpg"
    },
    {
      "name":"Dr. Sandra Meyer",
      "specialist":"orthopedic surgeon",
      "phone":"7116413918",
      "hospital":"Blue Ridge Medical",
      "onlineHours":"Fri-Wed, 10 AM - 1 PM",
      "hospitalHours":"Sun-Mon, 5 PM - 8 PM",
      "weekendAvailability":"Sun, 2 PM - 5 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/19.jpg"
    },
    {
      "name":"Dr. Deborah Barnes",
      "specialist":"Neurologist",
      "phone":"2535052147",
      "hospital":"Blue Ridge Medical",
      "onlineHours":"Fri-Fri, 2 PM - 5 PM",
      "hospitalHours":"Fri-Sat, 9 AM - 12 PM",
      "weekendAvailability":"Sat, 10 AM - 1 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/20.jpg"
    },
    {
      "name":"Dr. Joshua English",
      "specialist":"Psychiatrist",
      "phone":"8212307639",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Wed-Tue, 8 AM - 11 AM",
      "hospitalHours":"Tue-Mon, 2 PM - 5 PM",
      "weekendAvailability":"Tue, 7 PM - 10 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/21.jpg"
    },
    {
      "name":"Dr. Donna Rangel",
      "specialist":"Endocrinologist",
      "phone":"9037985033",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Mon-Mon, 8 AM - 11 AM",
      "hospitalHours":"Thu-Sun, 2 PM - 5 PM",
      "weekendAvailability":"Tue, 2 PM - 5 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/22.jpg"
    },
    {
      "name":"Dr. Jonathan Foster",
      "specialist":"Cardiologist",
      "phone":"2189438422",
      "hospital":"Blue Ridge Medical",
      "onlineHours":"Sun-Sun, 9 AM - 12 PM",
      "hospitalHours":"Sat-Sat, 3 PM - 6 PM",
      "weekendAvailability":"Sun, 5 PM - 8 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/23.jpg"
    },
    {
      "name":"Dr. Laura Bell",
      "specialist":"Neurologist",
      "phone":"7694915490",
      "hospital":"Heartbeat Care Clinic",
      "onlineHours":"Sun-Thu, 11 PM - 2 AM",
      "hospitalHours":"Sat-Fri, 3 PM - 6 PM",
      "weekendAvailability":"Thu, 9 AM - 12 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/24.jpg"
    },
    {
      "name":"Dr. Glenn Medina",
      "specialist":"Radiologist",
      "phone":"9119924477",
      "hospital":"Blue Ridge Medical",
      "onlineHours":"Mon-Mon, 7 PM - 10 PM",
      "hospitalHours":"Wed-Sat, 6 PM - 9 PM",
      "weekendAvailability":"Fri, 6 PM - 9 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/25.jpg"
    },
    {
      "name":"Dr. Michelle Marquez",
      "specialist":"Dermatologist",
      "phone":"2042989266",
      "hospital":"SummitCare Clinic",
      "onlineHours":"Fri-Sat, 11 PM - 2 AM",
      "hospitalHours":"Fri-Sat, 3 PM - 6 PM",
      "weekendAvailability":"Sat, 11 PM - 2 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/26.jpg"
    },
    {
      "name":"Dr. Nancy Miller",
      "specialist":"orthopedic surgeon",
      "phone":"1563330253",
      "hospital":"Oakwood Health Institute",
      "onlineHours":"Thu-Sun, 10 AM - 1 PM",
      "hospitalHours":"Thu-Wed, 9 AM - 12 PM",
      "weekendAvailability":"Sat, 8 AM - 11 AM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/27.jpg"
    },
    {
      "name":"Dr. Allen Austin",
      "specialist":"Dermatologist",
      "phone":"4893837461",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Wed-Tue, 2 PM - 5 PM",
      "hospitalHours":"Sat-Sun, 6 PM - 9 PM",
      "weekendAvailability":"Sat, 10 AM - 1 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/28.jpg"
    },
    {
      "name":"Dr. Amy Ward",
      "specialist":"Endocrinologist",
      "phone":"2634225214",
      "hospital":"WellSpring Hospital",
      "onlineHours":"Thu-Tue, 9 AM - 12 PM",
      "hospitalHours":"Thu-Mon, 8 AM - 11 AM",
      "weekendAvailability":"Sat, 3 PM - 6 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/29.jpg"
    },
    {
      "name":"Dr. Gloria Cooke",
      "specialist":"Psychiatrist",
      "phone":"1108228716",
      "hospital":"Oakwood Health Institute",
      "onlineHours":"Sat-Sat, 9 AM - 12 PM",
      "hospitalHours":"Tue-Tue, 11 PM - 2 AM",
      "weekendAvailability":"Mon, 9 AM - 12 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/30.jpg"
    },
    {
      "name":"Dr. John Hood",
      "specialist":"Psychiatrist",
      "phone":"9894492980",
      "hospital":"Sunrise Health Center",
      "onlineHours":"Fri-Sat, 9 AM - 12 PM",
      "hospitalHours":"Wed-Fri, 7 PM - 10 PM",
      "weekendAvailability":"Sun, 2 PM - 5 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/31.jpg"
    },
    {
      "name":"Dr. James Anderson",
      "specialist":"orthopedic surgeon surgeon",
      "phone":"2042715482",
      "hospital":"Blue Ridge Medical",
      "onlineHours":"Sat-Sun, 10 AM - 1 PM",
      "hospitalHours":"Wed-Thu, 2 PM - 5 PM",
      "weekendAvailability":"Tue, 10 AM - 1 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/32.jpg"
    },
    {
      "name":"Dr. Benjamin Quinn",
      "specialist":"Psychiatrist",
      "phone":"8798326736",
      "hospital":"WellSpring Hospital",
      "onlineHours":"Thu-Tue, 9 AM - 12 PM",
      "hospitalHours":"Sat-Wed, 10 AM - 1 PM",
      "weekendAvailability":"Tue, 7 PM - 10 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/33.jpg"
    },
    {
      "name":"Dr. Jennifer Humphrey",
      "specialist":"Oncologist",
      "phone":"4743264410",
      "hospital":"Oakwood Health Institute",
      "onlineHours":"Wed-Thu, 6 PM - 9 PM",
      "hospitalHours":"Sat-Thu, 6 PM - 9 PM",
      "weekendAvailability":"Wed, 9 AM - 12 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/34.jpg"
    },
    {
      "name":"Dr. Collin Sexton",
      "specialist":"Gastroenterologist",
      "phone":"7671061152",
      "hospital":"WellSpring Hospital",
      "onlineHours":"Sun-Tue, 9 AM - 12 PM",
      "hospitalHours":"Tue-Tue, 6 PM - 9 PM",
      "weekendAvailability":"Tue, 10 AM - 1 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/35.jpg"
    },
    {
      "name":"Dr. Lauren Ponce",
      "specialist":"Neurologist",
      "phone":"6086454763",
      "hospital":"Metro General Hospital",
      "onlineHours":"Thu-Mon, 11 PM - 2 AM",
      "hospitalHours":"Fri-Mon, 9 AM - 12 PM",
      "weekendAvailability":"Wed, 11 PM - 2 AM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/36.jpg"
    },
    {
      "name":"Dr. Christopher Larson",
      "specialist":"Gastroenterologist",
      "phone":"4612808180",
      "hospital":"Blue Ridge Medical",
      "onlineHours":"Sat-Mon, 11 PM - 2 AM",
      "hospitalHours":"Sat-Mon, 8 AM - 11 AM",
      "weekendAvailability":"Tue, 10 AM - 1 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/37.jpg"
    },
    {
      "name":"Dr. James Ramirez",
      "specialist":"Radiologist",
      "phone":"9919602520",
      "hospital":"SummitCare Clinic",
      "onlineHours":"Sat-Mon, 7 PM - 10 PM",
      "hospitalHours":"Mon-Sat, 7 PM - 10 PM",
      "weekendAvailability":"Fri, 7 PM - 10 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/38.jpg"
    },
    {
      "name":"Dr. Christine Rivera",
      "specialist":"Gastroenterologist",
      "phone":"9395696357",
      "hospital":"WellSpring Hospital",
      "onlineHours":"Wed-Thu, 8 AM - 11 AM",
      "hospitalHours":"Wed-Tue, 6 PM - 9 PM",
      "weekendAvailability":"Sat, 6 PM - 9 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/39.jpg"
    },
    {
      "name":"Dr. Jonathan Ortiz",
      "specialist":"Cardiologist",
      "phone":"3269681542",
      "hospital":"Lakeside Medical Center",
      "onlineHours":"Wed-Sun, 6 PM - 9 PM",
      "hospitalHours":"Tue-Tue, 10 AM - 1 PM",
      "weekendAvailability":"Tue, 6 PM - 9 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/40.jpg"
    },
    {
      "name":"Dr. Pamela Gentry",
      "specialist":"Oncologist",
      "phone":"4894818052",
      "hospital":"Lakeside Medical Center",
      "onlineHours":"Fri-Sat, 8 AM - 11 AM",
      "hospitalHours":"Fri-Sun, 6 PM - 9 PM",
      "weekendAvailability":"Sat, 6 PM - 9 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/41.jpg"
    },
    {
      "name":"Dr. Megan Cox",
      "specialist":"Dermatologist",
      "phone":"5844835855",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Mon-Thu, 11 PM - 2 AM",
      "hospitalHours":"Thu-Mon, 10 AM - 1 PM",
      "weekendAvailability":"Sun, 11 PM - 2 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/42.jpg"
    },
    {
      "name":"Dr. Benjamin Perez",
      "specialist":"Cardiologist",
      "phone":"6013053778",
      "hospital":"Heartbeat Care Clinic",
      "onlineHours":"Wed-Mon, 2 PM - 5 PM",
      "hospitalHours":"Mon-Sat, 9 AM - 12 PM",
      "weekendAvailability":"Sat, 8 AM - 11 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/43.jpg"
    },
    {
      "name":"Dr. Lisa Greene",
      "specialist":"Psychiatrist",
      "phone":"4917413085",
      "hospital":"Metro General Hospital",
      "onlineHours":"Mon-Tue, 10 AM - 1 PM",
      "hospitalHours":"Fri-Sun, 8 AM - 11 AM",
      "weekendAvailability":"Thu, 7 PM - 10 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/44.jpg"
    },
    {
      "name":"Dr. Jack Vance",
      "specialist":"Oncologist",
      "phone":"9256725072",
      "hospital":"Metro General Hospital",
      "onlineHours":"Mon-Sat, 9 AM - 12 PM",
      "hospitalHours":"Mon-Sat, 6 PM - 9 PM",
      "weekendAvailability":"Fri, 11 PM - 2 AM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/45.jpg"
    },
    {
      "name":"Dr. Frederick Morris",
      "specialist":"Gastroenterologist",
      "phone":"6833650982",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Fri-Wed, 6 PM - 9 PM",
      "hospitalHours":"Wed-Sun, 2 PM - 5 PM",
      "weekendAvailability":"Sat, 6 PM - 9 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/46.jpg"
    },
    {
      "name":"Dr. Sarah Thornton",
      "specialist":"Dermatologist",
      "phone":"0592256406",
      "hospital":"SummitCare Clinic",
      "onlineHours":"Tue-Tue, 11 PM - 2 AM",
      "hospitalHours":"Mon-Sun, 10 AM - 1 PM",
      "weekendAvailability":"Thu, 8 AM - 11 AM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/47.jpg"
    },
    {
      "name":"Dr. Johnathan Carter",
      "specialist":"Psychiatrist",
      "phone":"4432313713",
      "hospital":"Lakeside Medical Center",
      "onlineHours":"Fri-Thu, 10 AM - 1 PM",
      "hospitalHours":"Thu-Wed, 6 PM - 9 PM",
      "weekendAvailability":"Wed, 8 AM - 11 AM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/48.jpg"
    },
    {
      "name":"Dr. Natasha Sanchez",
      "specialist":"orthopedic surgeon",
      "phone":"0558704263",
      "hospital":"WellSpring Hospital",
      "onlineHours":"Fri-Thu, 10 AM - 1 PM",
      "hospitalHours":"Tue-Thu, 6 PM - 9 PM",
      "weekendAvailability":"Mon, 2 PM - 5 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/49.jpg"
    },
    {
      "name":"Dr. Allen Wright",
      "specialist":"Radiologist",
      "phone":"1760451315",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Mon-Fri, 6 PM - 9 PM",
      "hospitalHours":"Tue-Thu, 10 AM - 1 PM",
      "weekendAvailability":"Fri, 6 PM - 9 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/50.jpg"
    },
    {
      "name":"Dr. Hannah Garcia",
      "specialist":"Oncologist",
      "phone":"5899259304",
      "hospital":"SummitCare Clinic",
      "onlineHours":"Mon-Sat, 2 PM - 5 PM",
      "hospitalHours":"Thu-Thu, 10 AM - 1 PM",
      "weekendAvailability":"Tue, 8 AM - 11 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/51.jpg"
    },
    {
      "name":"Dr. Melissa Green",
      "specialist":"Cardiologist",
      "phone":"9419071063",
      "hospital":"Blue Ridge Medical",
      "onlineHours":"Fri-Sat, 7 PM - 10 PM",
      "hospitalHours":"Fri-Mon, 8 AM - 11 AM",
      "weekendAvailability":"Tue, 6 PM - 9 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/52.jpg"
    },
    {
      "name":"Dr. Angela Gibson",
      "specialist":"Neurologist",
      "phone":"3934370239",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Wed-Fri, 10 AM - 1 PM",
      "hospitalHours":"Sat-Thu, 5 PM - 8 PM",
      "weekendAvailability":"Fri, 8 AM - 11 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/53.jpg"
    },
    {
      "name":"Dr. Andrew Davis",
      "specialist":"Cardiologist",
      "phone":"7865684662",
      "hospital":"Lakeside Medical Center",
      "onlineHours":"Sun-Fri, 3 PM - 6 PM",
      "hospitalHours":"Fri-Mon, 7 PM - 10 PM",
      "weekendAvailability":"Tue, 5 PM - 8 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/54.jpg"
    },
    {
      "name":"Dr. Stephanie Rivera",
      "specialist":"Oncologist",
      "phone":"8702053561",
      "hospital":"SummitCare Clinic",
      "onlineHours":"Wed-Sun, 11 PM - 2 AM",
      "hospitalHours":"Thu-Wed, 5 PM - 8 PM",
      "weekendAvailability":"Thu, 5 PM - 8 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/55.jpg"
    },
    {
      "name":"Dr. Bryan Miller",
      "specialist":"Pediatrician",
      "phone":"0447715448",
      "hospital":"WellSpring Hospital",
      "onlineHours":"Fri-Mon, 11 PM - 2 AM",
      "hospitalHours":"Sat-Mon, 7 PM - 10 PM",
      "weekendAvailability":"Tue, 11 PM - 2 AM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/56.jpg"
    },
    {
      "name":"Dr. Jacqueline Carter",
      "specialist":"Radiologist",
      "phone":"1530840166",
      "hospital":"Oakwood Health Institute",
      "onlineHours":"Mon-Tue, 8 AM - 11 AM",
      "hospitalHours":"Tue-Thu, 11 PM - 2 AM",
      "weekendAvailability":"Sun, 2 PM - 5 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/57.jpg"
    },
    {
      "name":"Dr. Michael Taylor",
      "specialist":"Pediatrician",
      "phone":"4502966334",
      "hospital":"Sunrise Health Center",
      "onlineHours":"Thu-Tue, 10 AM - 1 PM",
      "hospitalHours":"Thu-Sat, 11 PM - 2 AM",
      "weekendAvailability":"Thu, 2 PM - 5 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/58.jpg"
    },
    {
      "name":"Dr. Claire Nelson",
      "specialist":"orthopedic surgeon",
      "phone":"2566310673",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Fri-Sat, 7 PM - 10 PM",
      "hospitalHours":"Sat-Thu, 8 AM - 11 AM",
      "weekendAvailability":"Wed, 3 PM - 6 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/59.jpg"
    },
    {
      "name":"Dr. John Joseph",
      "specialist":"orthopedic surgeon",
      "phone":"4967415579",
      "hospital":"Heartbeat Care Clinic",
      "onlineHours":"Tue-Mon, 9 AM - 12 PM",
      "hospitalHours":"Sun-Sat, 2 PM - 5 PM",
      "weekendAvailability":"Wed, 7 PM - 10 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/60.jpg"
    },
    {
      "name":"Dr. James Banks",
      "specialist":"Cardiologist",
      "phone":"3908409059",
      "hospital":"Heartbeat Care Clinic",
      "onlineHours":"Wed-Wed, 6 PM - 9 PM",
      "hospitalHours":"Wed-Tue, 9 AM - 12 PM",
      "weekendAvailability":"Fri, 9 AM - 12 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/61.jpg"
    },
    {
      "name":"Dr. Calvin Gray",
      "specialist":"Cardiologist",
      "phone":"1803107020",
      "hospital":"Lakeside Medical Center",
      "onlineHours":"Sat-Tue, 3 PM - 6 PM",
      "hospitalHours":"Fri-Mon, 6 PM - 9 PM",
      "weekendAvailability":"Wed, 3 PM - 6 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/62.jpg"
    },
    {
      "name":"Dr. Jared Oneal",
      "specialist":"Radiologist",
      "phone":"5451858263",
      "hospital":"SummitCare Clinic",
      "onlineHours":"Thu-Thu, 8 AM - 11 AM",
      "hospitalHours":"Tue-Sun, 7 PM - 10 PM",
      "weekendAvailability":"Sun, 7 PM - 10 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/63.jpg"
    },
    {
      "name":"Dr. Krista Mooney",
      "specialist":"Gastroenterologist",
      "phone":"6819586844",
      "hospital":"Heartbeat Care Clinic",
      "onlineHours":"Tue-Wed, 3 PM - 6 PM",
      "hospitalHours":"Tue-Fri, 8 AM - 11 AM",
      "weekendAvailability":"Fri, 8 AM - 11 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/64.jpg"
    },
    {
      "name":"Dr. Michael Kemp",
      "specialist":"Gastroenterologist",
      "phone":"7677353844",
      "hospital":"Heartbeat Care Clinic",
      "onlineHours":"Tue-Wed, 6 PM - 9 PM",
      "hospitalHours":"Sun-Tue, 9 AM - 12 PM",
      "weekendAvailability":"Thu, 5 PM - 8 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/65.jpg"
    },
    {
      "name":"Dr. Grace Lewis",
      "specialist":"Psychiatrist",
      "phone":"3405399523",
      "hospital":"Heartbeat Care Clinic",
      "onlineHours":"Thu-Fri, 10 AM - 1 PM",
      "hospitalHours":"Fri-Sat, 3 PM - 6 PM",
      "weekendAvailability":"Sun, 11 PM - 2 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/66.jpg"
    },
    {
      "name":"Dr. Mark Clark",
      "specialist":"Oncologist",
      "phone":"4781566196",
      "hospital":"Heartbeat Care Clinic",
      "onlineHours":"Sun-Mon, 10 AM - 1 PM",
      "hospitalHours":"Tue-Sat, 3 PM - 6 PM",
      "weekendAvailability":"Fri, 5 PM - 8 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/67.jpg"
    },
    {
      "name":"Dr. James Johnson",
      "specialist":"Cardiologist",
      "phone":"5326223791",
      "hospital":"Heartbeat Care Clinic",
      "onlineHours":"Wed-Sun, 7 PM - 10 PM",
      "hospitalHours":"Mon-Tue, 5 PM - 8 PM",
      "weekendAvailability":"Sat, 9 AM - 12 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/68.jpg"
    },
    {
      "name":"Dr. Deborah Romero",
      "specialist":"Pediatrician",
      "phone":"2310749878",
      "hospital":"WellSpring Hospital",
      "onlineHours":"Sat-Sun, 5 PM - 8 PM",
      "hospitalHours":"Fri-Sun, 2 PM - 5 PM",
      "weekendAvailability":"Tue, 6 PM - 9 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/69.jpg"
    },
    {
      "name":"Dr. Kimberly Estrada",
      "specialist":"Gastroenterologist",
      "phone":"2451234315",
      "hospital":"Oakwood Health Institute",
      "onlineHours":"Sat-Tue, 9 AM - 12 PM",
      "hospitalHours":"Thu-Fri, 2 PM - 5 PM",
      "weekendAvailability":"Tue, 3 PM - 6 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/70.jpg"
    },
    {
      "name":"Dr. Ryan Blackburn",
      "specialist":"Cardiologist",
      "phone":"6049442480",
      "hospital":"Metro General Hospital",
      "onlineHours":"Sun-Fri, 2 PM - 5 PM",
      "hospitalHours":"Mon-Sun, 6 PM - 9 PM",
      "weekendAvailability":"Sat, 9 AM - 12 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/71.jpg"
    },
    {
      "name":"Dr. Christina Cole",
      "specialist":"Psychiatrist",
      "phone":"9641791517",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Sat-Fri, 9 AM - 12 PM",
      "hospitalHours":"Thu-Fri, 7 PM - 10 PM",
      "weekendAvailability":"Sat, 7 PM - 10 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/72.jpg"
    },
    {
      "name":"Dr. Terri Perez",
      "specialist":"Psychiatrist",
      "phone":"8093469330",
      "hospital":"Evergreen Hospital",
      "onlineHours":"Sun-Sun, 6 PM - 9 PM",
      "hospitalHours":"Sun-Mon, 3 PM - 6 PM",
      "weekendAvailability":"Sun, 6 PM - 9 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/73.jpg"
    },
    {
      "name":"Dr. Mark Rivera",
      "specialist":"orthopedic surgeon",
      "phone":"8004798844",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Wed-Wed, 3 PM - 6 PM",
      "hospitalHours":"Sun-Sun, 9 AM - 12 PM",
      "weekendAvailability":"Tue, 9 AM - 12 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/74.jpg"
    },
    {
      "name":"Dr. Catherine Perkins",
      "specialist":"orthopedic surgeon",
      "phone":"9687374844",
      "hospital":"Metro General Hospital",
      "onlineHours":"Sun-Tue, 9 AM - 12 PM",
      "hospitalHours":"Fri-Tue, 7 PM - 10 PM",
      "weekendAvailability":"Sun, 8 AM - 11 AM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/75.jpg"
    },
    {
      "name":"Dr. Erin Skinner",
      "specialist":"Gastroenterologist",
      "phone":"8675649696",
      "hospital":"WellSpring Hospital",
      "onlineHours":"Wed-Thu, 8 AM - 11 AM",
      "hospitalHours":"Wed-Sat, 7 PM - 10 PM",
      "weekendAvailability":"Fri, 11 PM - 2 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/76.jpg"
    },
    {
      "name":"Dr. Steven Pacheco",
      "specialist":"Psychiatrist",
      "phone":"1080308006",
      "hospital":"Metro General Hospital",
      "onlineHours":"Tue-Thu, 9 AM - 12 PM",
      "hospitalHours":"Sun-Wed, 6 PM - 9 PM",
      "weekendAvailability":"Thu, 6 PM - 9 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/77.jpg"
    },
    {
      "name":"Dr. Kyle Gilmore",
      "specialist":"Neurologist",
      "phone":"1310969106",
      "hospital":"Lakeside Medical Center",
      "onlineHours":"Thu-Mon, 8 AM - 11 AM",
      "hospitalHours":"Sat-Sun, 3 PM - 6 PM",
      "weekendAvailability":"Wed, 6 PM - 9 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/78.jpg"
    },
    {
      "name":"Dr. Michelle Powell",
      "specialist":"Neurologist",
      "phone":"4718502927",
      "hospital":"WellSpring Hospital",
      "onlineHours":"Thu-Thu, 9 AM - 12 PM",
      "hospitalHours":"Sat-Wed, 3 PM - 6 PM",
      "weekendAvailability":"Mon, 9 AM - 12 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/79.jpg"
    },
    {
      "name":"Dr. Melanie Horn",
      "specialist":"Dermatologist",
      "phone":"7757758748",
      "hospital":"Lakeside Medical Center",
      "onlineHours":"Mon-Sun, 5 PM - 8 PM",
      "hospitalHours":"Fri-Sun, 7 PM - 10 PM",
      "weekendAvailability":"Tue, 3 PM - 6 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/80.jpg"
    },
    {
      "name":"Dr. Christina Osborne",
      "specialist":"Endocrinologist",
      "phone":"1310911440",
      "hospital":"SummitCare Clinic",
      "onlineHours":"Thu-Wed, 10 AM - 1 PM",
      "hospitalHours":"Sat-Mon, 6 PM - 9 PM",
      "weekendAvailability":"Sun, 5 PM - 8 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/81.jpg"
    },
    {
      "name":"Dr. Ann Wheeler",
      "specialist":"orthopedic surgeon",
      "phone":"7103188762",
      "hospital":"Sunrise Health Center",
      "onlineHours":"Mon-Thu, 3 PM - 6 PM",
      "hospitalHours":"Thu-Tue, 11 PM - 2 AM",
      "weekendAvailability":"Wed, 11 PM - 2 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/82.jpg"
    },
    {
      "name":"Dr. Matthew Carter",
      "specialist":"orthopedic surgeon",
      "phone":"6569275098",
      "hospital":"Sunrise Health Center",
      "onlineHours":"Sun-Fri, 3 PM - 6 PM",
      "hospitalHours":"Tue-Tue, 3 PM - 6 PM",
      "weekendAvailability":"Sat, 6 PM - 9 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/83.jpg"
    },
    {
      "name":"Dr. Brenda Wong",
      "specialist":"Cardiologist",
      "phone":"4756248961",
      "hospital":"Metro General Hospital",
      "onlineHours":"Sat-Sun, 10 AM - 1 PM",
      "hospitalHours":"Mon-Thu, 9 AM - 12 PM",
      "weekendAvailability":"Mon, 3 PM - 6 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/84.jpg"
    },
    {
      "name":"Dr. Joshua Edwards",
      "specialist":"Neurologist",
      "phone":"8040426315",
      "hospital":"Evergreen Hospital",
      "onlineHours":"Wed-Tue, 8 AM - 11 AM",
      "hospitalHours":"Thu-Wed, 2 PM - 5 PM",
      "weekendAvailability":"Tue, 8 AM - 11 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/85.jpg"
    },
    {
      "name":"Dr. Thomas Summers",
      "specialist":"Endocrinologist",
      "phone":"2575978668",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Thu-Mon, 8 AM - 11 AM",
      "hospitalHours":"Sun-Tue, 5 PM - 8 PM",
      "weekendAvailability":"Mon, 3 PM - 6 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/86.jpg"
    },
    {
      "name":"Dr. Tracy Sutton",
      "specialist":"Endocrinologist",
      "phone":"2157011667",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Mon-Thu, 3 PM - 6 PM",
      "hospitalHours":"Tue-Fri, 6 PM - 9 PM",
      "weekendAvailability":"Sun, 3 PM - 6 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/87.jpg"
    },
    {
      "name":"Dr. Brenda Cox",
      "specialist":"Neurologist",
      "phone":"4104444561",
      "hospital":"SummitCare Clinic",
      "onlineHours":"Thu-Mon, 9 AM - 12 PM",
      "hospitalHours":"Wed-Tue, 6 PM - 9 PM",
      "weekendAvailability":"Sun, 7 PM - 10 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/88.jpg"
    },
    {
      "name":"Dr. Andrew Dunn",
      "specialist":"orthopedic surgeon",
      "phone":"3955070403",
      "hospital":"Metro General Hospital",
      "onlineHours":"Thu-Mon, 2 PM - 5 PM",
      "hospitalHours":"Sun-Mon, 8 AM - 11 AM",
      "weekendAvailability":"Sat, 10 AM - 1 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/89.jpg"
    },
    {
      "name":"Dr. Barbara Neal",
      "specialist":"Cardiologist",
      "phone":"8958517313",
      "hospital":"Green Valley Children's Hospital",
      "onlineHours":"Wed-Thu, 10 AM - 1 PM",
      "hospitalHours":"Tue-Sun, 7 PM - 10 PM",
      "weekendAvailability":"Sat, 9 AM - 12 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/90.jpg"
    },
    {
      "name":"Dr. Cynthia Cisneros",
      "specialist":"orthopedic surgeon",
      "phone":"3115424088",
      "hospital":"Metro General Hospital",
      "onlineHours":"Sat-Mon, 7 PM - 10 PM",
      "hospitalHours":"Fri-Wed, 9 AM - 12 PM",
      "weekendAvailability":"Fri, 7 PM - 10 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/91.jpg"
    },
    {
      "name":"Dr. Erica Randall",
      "specialist":"Endocrinologist",
      "phone":"3306248587",
      "hospital":"Oakwood Health Institute",
      "onlineHours":"Tue-Fri, 5 PM - 8 PM",
      "hospitalHours":"Thu-Sat, 7 PM - 10 PM",
      "weekendAvailability":"Sat, 8 AM - 11 AM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/92.jpg"
    },
    {
      "name":"Dr. Ashley Pope",
      "specialist":"Cardiologist",
      "phone":"6860777123",
      "hospital":"Oakwood Health Institute",
      "onlineHours":"Thu-Sun, 7 PM - 10 PM",
      "hospitalHours":"Fri-Sat, 7 PM - 10 PM",
      "weekendAvailability":"Thu, 11 PM - 2 AM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/93.jpg"
    },
    {
      "name":"Dr. Amy Kelley",
      "specialist":"orthopedic surgeon",
      "phone":"9639692118",
      "hospital":"Blue Ridge Medical",
      "onlineHours":"Fri-Tue, 7 PM - 10 PM",
      "hospitalHours":"Mon-Sun, 5 PM - 8 PM",
      "weekendAvailability":"Tue, 9 AM - 12 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/94.jpg"
    },
    {
      "name":"Dr. Wanda Chen",
      "specialist":"Pediatrician",
      "phone":"1478412406",
      "hospital":"Sunrise Health Center",
      "onlineHours":"Wed-Thu, 2 PM - 5 PM",
      "hospitalHours":"Mon-Mon, 7 PM - 10 PM",
      "weekendAvailability":"Sun, 10 AM - 1 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/95.jpg"
    },
    {
      "name":"Dr. Sonya Reyes",
      "specialist":"Dermatologist",
      "phone":"9110274368",
      "hospital":"Evergreen Hospital",
      "onlineHours":"Mon-Wed, 3 PM - 6 PM",
      "hospitalHours":"Sat-Tue, 9 AM - 12 PM",
      "weekendAvailability":"Thu, 7 PM - 10 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/96.jpg"
    },
    {
      "name":"Dr. Ashley Gutierrez",
      "specialist":"Oncologist",
      "phone":"7236134745",
      "hospital":"Sunrise Health Center",
      "onlineHours":"Tue-Sat, 3 PM - 6 PM",
      "hospitalHours":"Thu-Sat, 6 PM - 9 PM",
      "weekendAvailability":"Mon, 7 PM - 10 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/97.jpg"
    },
    {
      "name":"Dr. Joseph Duncan",
      "specialist":"Cardiologist",
      "phone":"9781505731",
      "hospital":"Blue Ridge Medical",
      "onlineHours":"Sun-Sat, 11 PM - 2 AM",
      "hospitalHours":"Tue-Fri, 3 PM - 6 PM",
      "weekendAvailability":"Thu, 7 PM - 10 PM",
      "emergencyAvailable":true,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/men\/98.jpg"
    },
    {
      "name":"Dr. Natalie Mclaughlin",
      "specialist":"Dermatologist",
      "phone":"8173277312",
      "hospital":"SummitCare Clinic",
      "onlineHours":"Fri-Fri, 9 AM - 12 PM",
      "hospitalHours":"Sat-Tue, 3 PM - 6 PM",
      "weekendAvailability":"Sat, 2 PM - 5 PM",
      "emergencyAvailable":false,
      "photo":"https:\/\/randomuser.me\/api\/portraits\/women\/99.jpg"
    }
  ]
  
export default doctorData;